# Generated by Django 3.0.9 on 2020-12-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.BigIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('priceperUnit', models.PositiveIntegerField()),
                ('totalprice', models.PositiveIntegerField(editable=False)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='NotificationListView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('orderamount', models.IntegerField()),
                ('getbydate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=2)),
                ('Name', models.CharField(max_length=10)),
                ('consrate', models.PositiveIntegerField()),
                ('delivery', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.BigIntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
