# Generated by Django 3.0.9 on 2021-01-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0003_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='invoiceid',
            field=models.BigIntegerField(null=True),
        ),
    ]
