# Generated by Django 3.0.9 on 2021-01-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0004_stock_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='invoiceid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
